# Use official Node.js image for Next.js
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's files
#COPY . ./

# Expose port for Next.js (default 3000)
EXPOSE 3000

# Start the Next.js app in production mode
CMD ["npm", "run", "dev"]
